# 服务配置
server:
  port: 8001
# mybatis配置
mybatis:
  type-aliases-package: com.kdemo.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
# Eureka
eureka:
  client:
    service-url:
      # 要用与Eureka注册中心所配置的地址相同, 才能注册上服务, 需要同时注册到集群每一台eureka上
#      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
# 描述项目基本信息
info:
  app:
    name: springcloud-provider-dept-8001
    port: ${server.port}
    version: 1.0.0