server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com # Eureka 服务端实例
  client:
    register-with-eureka: false # 是否向Eureka注册自己
    fetch-registry: false # 如果为false标识自己为注册中心, true是寻找注册中心
    service-url: # Eureka注册中心的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

