server:
  port: 8887

spring:
  application:
    name: nacos-consumer
  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # Redis - Config
  redis:
    # single
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# use okhttp to do the feign request
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  # must be configured -> then we can find it by name on Prometheus Metrics -> Grafana dashboard
  metrics:
    tags:
      application: ${spring.application.name}

#logging:
#  pattern:
#    console: "%date{yy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} --- [%15.15t] %-40.40logger{39}[%4line]: %msg%n trace_id=%X{trace_id}%n"

grpc:
  client:
    GLOBAL:
      # client需要与server选择同样配置
      negotiation-type: plaintext
