# logging
logging:
  level:
    root: DEBUG
    sun.rmi: INFO
    javax.management.remote.rmi: INFO

#spring:
#  dynamic:
#    tp:
#      enabledCollect: true                 # 是否开启监控指标采集，默认false
#      collectorTypes: micrometer           # 监控数据采集器类型（logging | micrometer | internal_logging | JMX），默认micrometer
#      monitorInterval: 5                   # 监控时间间隔（报警判断、指标采集），默认5s
#      dubboTp: # dubbo 线程池配置
#        - threadPoolName: dubboTp#20202    # 名称规则：dubboTp + "#" + 协议端口
#          threadPoolAliasName: 测试线程池
#          corePoolSize: 100
#          maximumPoolSize: 200
#          keepAliveTime: 60
#          runTimeout: 200
#          queueTimeout: 100

# dubbo config
dubbo:
  application:
    name: dubbo-v2-producer
    parameters:
      protocol: dubbo
    qos-enable: true
    qos-port: 20202
  # dubbo rpc registry
  registry:
    address: nacos://localhost:8848 # on intellij
    #    address: nacos://192.168.215.2:8848 # in docker img
    protocol: dubbo
    timeout: 2000
    serialization: hessian2
    corethreads: 4
  # dubbo rpc protocol
  protocol:
    name: dubbo
    port: 20203
    telnet: ls,ps,cd,pwd,trace,count,invoke,select,status,log,help,clear,exit,shutdown
    threads: 2
    threadpool: cached
  # provider side
  provider:
    timeout: 20000
    retries: 0
    loadbalance: roundrobin
    threads: 2
    threadpool: cached
  # consumer side
  consumer:
    timeout: 20000
    retries: 0
    check: false
    loadbalance: roundrobin
    threads: 2