# logging
logging:
  level:
    root: DEBUG
    sun.rmi: INFO
    javax.management.remote.rmi: INFO
#  pattern:
#    console: '[%d{dd/MM/yy HH:mm:ss:SSS z}] %t %5p %c{2} [%X{traceId:-}, %X{spanId:-}]: %m%n'

# dubbo config
dubbo:
  application:
    name: dubbo-v2-consumer
    parameters:
      protocol: dubbo
    qos-enable: true
    qos-port: 20302
  # dubbo rpc registry
  registry:
    address: nacos://localhost:8848 # on intellij
    #    address: nacos://192.168.215.2:8848 # in docker img
    protocol: dubbo
    timeout: 2000
  protocol:
    name: dubbo
    port: 20303
    telnet: ls,ps,cd,pwd,trace,count,invoke,select,status,log,help,clear,exit,shutdown
  #    serialization: hessian2
  #    corethreads: 4
  # provider side
  provider:
    timeout: 20000 # 20s
    retries: 0
    loadbalance: roundrobin
  #    threads: 2
  #    threadpool: cached
  # consumer side
  consumer:
    timeout: 20000 # 20s
    retries: 0
    check: false
    loadbalance: roundrobin
#    threads: 2