server:
  port: 8888
spring:
  application:
    name: nacos-consumer
  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
grpc:
  client:
    GLOBAL:
      # client需要与server选择同样配置
      negotiation-type: plaintext