management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

logging:
  pattern:
    console: "%date{yy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} --- [%15.15t] %-40.40logger{39}[%4line]: %msg%n"
