server:
  port: 9900

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://example.org
          predicates:
            - Method=GET, POST