server:
  port: 8080
eureka:
  client:
    register-with-eureka: false # 消费者不需要向eureka注册自己
    service-url: # 可以从3个注册中心进行获取
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
# ribbon 饥饿加载
ribbon:
  eager-load:
    enabled: true